// AUTO-GENERATED by scripts/gen-emoji.mjs - do not edit by hand.
// HD vector stickers (Twemoji, CC-BY 4.0). Each renders from /emoji/<code>.svg.
export type Emoji = { char: string; code: string };

export const EMOJI: Emoji[] = [
  {
    "char": "😀",
    "code": "1f600"
  },
  {
    "char": "😂",
    "code": "1f602"
  },
  {
    "char": "🥰",
    "code": "1f970"
  },
  {
    "char": "😍",
    "code": "1f60d"
  },
  {
    "char": "😎",
    "code": "1f60e"
  },
  {
    "char": "🤩",
    "code": "1f929"
  },
  {
    "char": "🥳",
    "code": "1f973"
  },
  {
    "char": "😭",
    "code": "1f62d"
  },
  {
    "char": "🙃",
    "code": "1f643"
  },
  {
    "char": "😴",
    "code": "1f634"
  },
  {
    "char": "❤️",
    "code": "2764"
  },
  {
    "char": "🧡",
    "code": "1f9e1"
  },
  {
    "char": "💛",
    "code": "1f49b"
  },
  {
    "char": "💚",
    "code": "1f49a"
  },
  {
    "char": "💙",
    "code": "1f499"
  },
  {
    "char": "💜",
    "code": "1f49c"
  },
  {
    "char": "🖤",
    "code": "1f5a4"
  },
  {
    "char": "🤍",
    "code": "1f90d"
  },
  {
    "char": "💖",
    "code": "1f496"
  },
  {
    "char": "💯",
    "code": "1f4af"
  },
  {
    "char": "🔥",
    "code": "1f525"
  },
  {
    "char": "✨",
    "code": "2728"
  },
  {
    "char": "⭐️",
    "code": "2b50"
  },
  {
    "char": "🌟",
    "code": "1f31f"
  },
  {
    "char": "💫",
    "code": "1f4ab"
  },
  {
    "char": "🌈",
    "code": "1f308"
  },
  {
    "char": "☀️",
    "code": "2600"
  },
  {
    "char": "🌙",
    "code": "1f319"
  },
  {
    "char": "⚡️",
    "code": "26a1"
  },
  {
    "char": "❄️",
    "code": "2744"
  },
  {
    "char": "🎉",
    "code": "1f389"
  },
  {
    "char": "🎈",
    "code": "1f388"
  },
  {
    "char": "🎂",
    "code": "1f382"
  },
  {
    "char": "🎁",
    "code": "1f381"
  },
  {
    "char": "🏆",
    "code": "1f3c6"
  },
  {
    "char": "👑",
    "code": "1f451"
  },
  {
    "char": "💐",
    "code": "1f490"
  },
  {
    "char": "🌸",
    "code": "1f338"
  },
  {
    "char": "🌺",
    "code": "1f33a"
  },
  {
    "char": "🌻",
    "code": "1f33b"
  },
  {
    "char": "🍕",
    "code": "1f355"
  },
  {
    "char": "🍔",
    "code": "1f354"
  },
  {
    "char": "🍟",
    "code": "1f35f"
  },
  {
    "char": "🌮",
    "code": "1f32e"
  },
  {
    "char": "🍿",
    "code": "1f37f"
  },
  {
    "char": "🍩",
    "code": "1f369"
  },
  {
    "char": "🍦",
    "code": "1f366"
  },
  {
    "char": "☕️",
    "code": "2615"
  },
  {
    "char": "🍺",
    "code": "1f37a"
  },
  {
    "char": "🥂",
    "code": "1f942"
  },
  {
    "char": "📸",
    "code": "1f4f8"
  },
  {
    "char": "🎧",
    "code": "1f3a7"
  },
  {
    "char": "🎸",
    "code": "1f3b8"
  },
  {
    "char": "🎮",
    "code": "1f3ae"
  },
  {
    "char": "⚽️",
    "code": "26bd"
  },
  {
    "char": "🏀",
    "code": "1f3c0"
  },
  {
    "char": "🏖️",
    "code": "1f3d6"
  },
  {
    "char": "🌊",
    "code": "1f30a"
  },
  {
    "char": "🗺️",
    "code": "1f5fa"
  },
  {
    "char": "🚀",
    "code": "1f680"
  },
  {
    "char": "🐶",
    "code": "1f436"
  },
  {
    "char": "🐱",
    "code": "1f431"
  },
  {
    "char": "🐼",
    "code": "1f43c"
  },
  {
    "char": "🦄",
    "code": "1f984"
  },
  {
    "char": "🐢",
    "code": "1f422"
  },
  {
    "char": "🦋",
    "code": "1f98b"
  },
  {
    "char": "👍",
    "code": "1f44d"
  },
  {
    "char": "🙌",
    "code": "1f64c"
  },
  {
    "char": "🤙",
    "code": "1f919"
  },
  {
    "char": "✌️",
    "code": "270c"
  }
];

/** Twemoji codepoint filename for an emoji character (strips U+FE0F). */
export function emojiCode(ch: string): string {
  return [...ch]
    .map((c) => (c.codePointAt(0) ?? 0).toString(16))
    .filter((h) => h !== "fe0f")
    .join("-");
}

export function emojiSrc(code: string): string {
  return `/emoji/${code}.svg`;
}
