// Downloads HD vector (Twemoji) SVGs for the sticker set into /public/emoji and
// regenerates src/lib/emoji.ts. Run: node scripts/gen-emoji.mjs
// Twemoji is CC-BY 4.0 (Twitter/jdecked) - see README credit.
import { mkdir, writeFile, rm } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "public", "emoji");
const BASE = "https://cdn.jsdelivr.net/gh/jdecked/twemoji@15.1.0/assets/svg";

const CHARS = [
  "😀","😂","🥰","😍","😎","🤩","🥳","😭","🙃","😴",
  "❤️","🧡","💛","💚","💙","💜","🖤","🤍","💖","💯",
  "🔥","✨","⭐️","🌟","💫","🌈","☀️","🌙","⚡️","❄️",
  "🎉","🎈","🎂","🎁","🏆","👑","💐","🌸","🌺","🌻",
  "🍕","🍔","🍟","🌮","🍿","🍩","🍦","☕️","🍺","🥂",
  "📸","🎧","🎸","🎮","⚽️","🏀","🏖️","🌊","🗺️","🚀",
  "🐶","🐱","🐼","🦄","🐢","🦋","👍","🙌","🤙","✌️",
];

function codepoints(ch, keepVs) {
  return [...ch]
    .map((c) => (c.codePointAt(0) ?? 0).toString(16))
    .filter((h) => keepVs || h !== "fe0f")
    .join("-");
}

async function fetchSvg(code) {
  const res = await fetch(`${BASE}/${code}.svg`);
  return res.ok ? await res.text() : null;
}

async function main() {
  await rm(OUT, { recursive: true, force: true });
  await mkdir(OUT, { recursive: true });
  const out = [];
  for (const ch of CHARS) {
    let code = codepoints(ch, false);
    let svg = await fetchSvg(code);
    if (!svg) {
      code = codepoints(ch, true);
      svg = await fetchSvg(code);
    }
    if (!svg) {
      console.warn("skip (no twemoji):", ch, codepoints(ch, false));
      continue;
    }
    svg = svg.replace("<svg ", '<svg width="36" height="36" ');
    await writeFile(path.join(OUT, `${code}.svg`), svg);
    out.push({ char: ch, code });
  }
  const ts = `// AUTO-GENERATED by scripts/gen-emoji.mjs - do not edit by hand.
// HD vector stickers (Twemoji, CC-BY 4.0). Each renders from /emoji/<code>.svg.
export type Emoji = { char: string; code: string };

export const EMOJI: Emoji[] = ${JSON.stringify(out, null, 2)};

/** Twemoji codepoint filename for an emoji character (strips U+FE0F). */
export function emojiCode(ch: string): string {
  return [...ch]
    .map((c) => (c.codePointAt(0) ?? 0).toString(16))
    .filter((h) => h !== "fe0f")
    .join("-");
}

export function emojiSrc(code: string): string {
  return \`/emoji/\${code}.svg\`;
}
`;
  await writeFile(path.join(ROOT, "src", "lib", "emoji.ts"), ts);
  console.log(`emoji: wrote ${out.length} svgs + src/lib/emoji.ts`);
}

main().catch((e) => { console.error(e); process.exit(1); });
